env:
  contexts:
    - name: juice
      urls: [ "http://host.docker.internal:3000" ]
  parameters:
    failOnError: false
    progressToStdout: true
jobs:
  - type: spider
    parameters:
      url: "http://host.docker.internal:3000"
      maxDuration: 2
  - type: passiveScan-wait
  - type: report
    parameters:
      template: traditional-html
      reportDir: /zap/wrk
      reportFile: zap-baseline
      reportTitle: "DAST Baseline Juice Shop - ds-235150200111012"
  - type: report
    parameters:
      template: traditional-json
      reportDir: /zap/wrk
      reportFile: zap-baseline
